services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:9000 --workers 3 taskmanager.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "9000:9000"
    env_file:
      - .env
    # Database dependency removed - using SQLite by default
    # Uncomment below if using PostgreSQL
    # depends_on:
    #   - db

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=taskmanager_db
      - POSTGRES_USER=taskmanager_user
      - POSTGRES_PASSWORD=taskmanager_pass

volumes:
  postgres_data:
  static_volume:
